# Generated by Django 4.1.6 on 2023-02-11 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appboard', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name='Отклик')),
                ('status', models.CharField(choices=[('C', 'Создано'), ('A', 'Принято'), ('D', 'Отклонено')], default='C', max_length=1, verbose_name='Статус')),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='appboard.post')),
            ],
        ),
    ]
